admin/urls.py
from django.urls import path

from .views import views, category_view, blog_view, comment_view, like_view, user_view, profile_view

app_name = 'admin'
urlpatterns = [
    path('', views.index, name='index'),
    # categories
    path('categories', category_view.index, name='categories.index'),
    path('categories/create', category_view.create, name='categories.create'),
    path('categories/store', category_view.store, name='categories.store'),
    path('categories/<int:category_id>', category_view.update, name='categories.update'),
    path('categories/<int:category_id>/delete', category_view.destroy, name='categories.destroy'),
    path('categories/<int:category_id>/show', category_view.show, name='categories.show'),
    path('categories/<int:category_id>/edit', category_view.edit, name='categories.edit'),

    # blogs
    path('blogs', blog_view.index, name='blogs.index'),
    path('blogs/create', blog_view.create, name='blogs.create'),
    path('blogs/store', blog_view.store, name='blogs.store'),
    path('blogs/<int:blog_id>/delete', blog_view.destroy, name='blogs.destroy'),
    path('blog/<int:blog_id>/edit', blog_view.edit, name='blogs.edit'),
    path('blog/<int:blog_id>', blog_view.update, name='blogs.update'),
    path('blog/<int:blog_id>/show', blog_view.show, name='blogs.show'),

    # comments
    path('blog/<int:blog_id>/comments', comment_view.store, name='comments.store'),
    path('blog/<int:blog_id>/comments/<int:comment_id>/edit', comment_view.edit, name='comments.edit'),
    path('comments/<int:comment_id>', comment_view.update, name='comments.update'),
    path('comments/<int:comment_id>/delete', comment_view.destroy, name='comments.destroy'),
    path('comments/<int:comment_id>/toggle_visibility', comment_view.toggle_visibility, name='comments.toggle_visibility'),

    # like
    path('blog/<int:blog_id>/like/store', like_view.store, name='like.store'),
    path('blog/<int:blog_id>/like/delete', like_view.destroy, name='like.destroy'),

    # users
    path('users', user_view.index, name='users.index'),
    path('user/<int:user_id>/ban', user_view.toggle_ban, name='users.toggle_ban'),
    path('user/<int:user_id>/show', user_view.show, name='users.show'),
    path('users/create', user_view.create, name='users.create'),
    path('users/store', user_view.store, name='users.store'),

    # profile
    path('profile/<int:profile_id>', profile_view.update, name='profiles.update')
]

frontend/urls.py
from . import views
from django.urls import path

app_name = 'frontend'
urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.register, name='register'),
    path('signup', views.signup, name='signup'),
    path('login', views.login_view, name='login'),
    path('categories/<int:id>', views.show_category, name='categories.show'),

    # blog
    path('blog/<int:id>', views.show_blog, name='blogs.show')
]

mysite/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('frontend.urls')),
    path('admin/', include('admin.urls')),
    path('auth/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils import timezone


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'

    title = models.CharField(max_length=30)
    description = models.TextField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def __str__(self):
        return self.title


class Blog(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False, related_name='blogs')
    likes = models.ManyToManyField(User, through='Like', through_fields=('blog', 'user'), related_name='blog')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, related_name='blogs')
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def __str__(self):
        return self.title

    def is_liked_by(self, user):
        return self.like_set.filter(user_id=user.id).exists()


class Comment(models.Model):

    def __str__(self):
        return self.content

    content = models.TextField(max_length=200)
    is_hidden = models.BooleanField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False, related_name='comments')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    pub_date = models.DateTimeField('date published', default=timezone.now)


class Like(models.Model):
    class Meta:
        unique_together = ("user", "blog")

    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    liked_at = models.DateTimeField('liked at', default=timezone.now)


class Profile(models.Model):
    DEFAULT_IMAGE_URL = 'default.png'
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=200, blank=True, null=True)
    image = models.ImageField(upload_to='uploads', blank=True, null=True, default=DEFAULT_IMAGE_URL)

    def has_default_image(self):
        return self.image == self.DEFAULT_IMAGE_URL

    def set_image_to_default(self):
        if not self.has_default_image():
            self.image.delete()
            self.image = self.DEFAULT_IMAGE_URL
            self.save()
        return self

frontend/views.py
from django.contrib.auth import login
from django.db.models import Count, Q
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from frontend.models import Category, Blog, Profile
from admin.forms import CommentForm


def home(request):
    query = request.GET.get('query')
    blogs = Blog.objects.annotate(visible_comments=Count('comments', filter=Q(comments__is_hidden=False)))
    if query:
        blogs = blogs.filter(title__icontains=query)

    return render(request, 'frontend/home.html', {
        'blogs': blogs,
    })


def show_category(request, id):
    category_to_show = Category.objects.get(pk=id)
    query = request.GET.get('query')
    blogs = category_to_show.blogs.all()
    if query:
        blogs = blogs.filter(title__icontains=query)

    return render(request, 'frontend/categories/show.html', {
        'category_to_show': category_to_show,
        'blogs': blogs,
    })


def show_blog(request, id):
    blog = Blog.objects.get(pk=id)
    visible_comments = blog.comments.filter(is_hidden=False)
    is_liked = blog.is_liked_by(request.user)
    form = CommentForm()
    return render(request, 'frontend/blogs/show.html', {
        'blog': blog,
        'is_liked': is_liked,
        'visible_comments': visible_comments,
        'form': form,
    })


def register(request):
    form = UserCreationForm()
    return render(request, 'frontend/pages/registration.html', {'form': form})


def signup(request):
    form = UserCreationForm(request.POST)
    if form.is_valid():
        user = form.save()
        Profile.objects.create(user=user)
        login(request, user)
        messages.success(request, "Welcome to the administration board!")
    else:
        return render(request, 'frontend/pages/registration.html', {'form': form})

    return redirect('admin:index')


def login_view(request):
    form = AuthenticationForm(data=request.POST)
    if form.is_valid():
        user = form.get_user()
        login(request, user)
        messages.success(request, "You are logged in!")
        if 'next' in request.POST:
            redirect(request.POST.get('next'))
        return redirect('admin:index')

    return redirect('frontend:home')

frontend/templates/frontend/layouts/card.html
<div class="ui card">
  <div class="image">
    <img src="{{ user.profile.image.url }}" class="medium circular image">
  </div>
  <div class="content">
    <a class="header">{{ user.username }}</a>
    <div class="meta">
      <span class="date">Joined in {{ user.date_joined }}</span>
    </div>
    <div class="description">
      {{ user.profile.description }}
    </div>

    <hr>
    <div class="two ui buttons">
      <button class="button ui">
        <a href="{% url 'admin:index' %}" target="_blank">Backend</a>
      </button>
      <button class="button ui">
        <a href="{% url 'logout' %}">Logout </a>
      </button>
    </div>
  </div>

</div>

frontend/templates/frontend/layouts/login.html
<div class="ui raised segment blue">
  <h2>Login</h2>
  <form method="POST" action="{% url 'frontend:login' %}" class="ui form">
    {% csrf_token %}
    <div class="field">
      {{ login_form.username.errors }}
      {{ login_form.username.label_tag }}
      {{ login_form.username }}
    </div>

    <div class="field">
      {{ login_form.password.errors }}
      {{ login_form.password.label_tag }}
      {{ login_form.password }}
    </div>
    {% if request.GET.next %}
       <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <div class="two ui buttons">
      <button class="button ui primary" type="submit">Login</button>
      <div class="or"></div>
      <button class="button ui positive" type="button">
        <a href="{% url 'frontend:register' %}" style="color: inherit">Register</a>
      </button>
    </div>
  </form>
</div>

frontend/templates/frontend/layouts/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.css">
  <link rel="stylesheet" href="{% static 'frontend/css/frontend.css' %}">
  <title> {% block title %} {% endblock %} </title>
</head>
<body>
<div class="ui container">
  <div class="ui grid" style="padding-top: 30px;">
    <div class="row">
      <div class="twelve wide column">
        <div class="ui huge breadcrumb">
          {% block breadcrumb %}
            <a class="section" href="{% url 'frontend:home' %}">My Coolest Blog</a>
            <i class="right chevron icon divider"></i>
          {% endblock %}
        </div>
      </div>
      <div class="four wide column">
        {% include 'frontend/layouts/search_form.html' %}
      </div>
    </div>
    <div class="row">
      <div class="four wide column">
        {% include 'frontend/layouts/sidebar.html' %}
      </div>
      <div class="eight wide column">

        {% block content %}
        {% endblock %}
      </div>
      <div class="four wide column">
        {% if user.is_authenticated %}
          {% include 'frontend/layouts/card.html' %}
        {% else %}
          {% include 'frontend/layouts/login.html' %}
        {% endif %}
      </div>
    </div>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.js"></script>
<script>
  {#  prevent user from submitting a form via Enter key, only textarea is allowed #}
  $(document).on("keypress", ":input:not(textarea)", function (event) {
    return event.keyCode !== 13;
  });
  {# icon for submitting form #}
  $('i[data-target]').click(function (e) {
    e.preventDefault();
    let target = $(this).data('target');
    $("#" + target).submit();
  });
</script>
{% block script %} {% endblock %}
</body>
</html>

frontend/templates/frontend/layouts/search_form.html
<form action="{{ request.path }}" method="GET" id="query_form">
  <div class="ui icon input fluid">
    <input type="text" placeholder="Search blog..." name="query">
    <i class="circular search link icon" data-target="query_form"></i>
  </div>
</form>

frontend/templates/frontend/layouts/sidebar.html
<h1>Categories</h1>
<div class="ui items">
  {% for category in categories %}
    <div class="item">
      <div class="content">
        <a href="{% url 'frontend:categories.show' category.id %}">{{ category.title }}</a>
      </div>
    </div>
  {% endfor %}
</div>